version: '3'

services:
    web:
        build: .
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.site_algo.rule=Host(`radio.lebbadi.fr`)"
          - "traefik.http.routers.site_algo.tls=true"
          - "traefik.http.routers.site_algo.tls.certresolver=myresolver"
          - "com.centurylinklabs.watchtower.enable=false"
        restart: always
        networks:
          - traefik_default

networks:
    traefik_default:
        external: true
